server:
  port: 3000
  servlet:
    session.cookie.name: b8a5f3fb
  use-forward-headers: true

spring:
  # 레디스 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  # 데이터베이스 설정
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}
    username: ${db.username}
    password: ${db.password}

  # JPA 및 Hibernate 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: ${ddl.auto}

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

# 로거 설정 - SQL 로그를 자세히 출력 (바인딩 값까지)
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

# 파일 업로드 경로 설정
file:
  upload:
    url: ${file.url}
    path: ${file.path}

# 파이썬 설정
python:
  path:
    # 경로 주입 받기
    base: ${python.base}
    trend: ${python.trend}
    base2: ${python.base2}
    restaurant: ${python.restaurant}

springdoc:
  version: '1.0.0'
  api-docs:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**

# 소셜 로그인 API 설정
social:
  kakao.apikey: ${kakao.apikey}
  #naver.apikey: ${naver.apikey}